About:blank has no more annoying borders
NebulaServices/Nebula pull request #195
Opened 2024-01-01 02:50 UTC by IncognitoTGT

This is not a shit pr

2024-01-01 04:36 UTC, IncognitoTGT commented
about:blank for entire nebula now

2024-01-01 16:33 UTC, cohenerickson requested changes
Attempt to abstract A:B cloaking and run prettier. Other than that it looks good

2024-01-01 16:33 UTC, cohenerickson commented on src/AboutBlank.tsx
>    iframe.style.height = "100%";
I don't know that having top, bottom, left, and right makes any difference but I could be wrong on this.

2024-01-01 16:33 UTC, cohenerickson commented on src/components/Header.tsx
> +              className="flex h-full w-full "
Run prettier

2024-01-01 16:33 UTC, cohenerickson commented on src/pages/Settings/TabSettings.tsx
> +              let newWindow = window.open("about:blank");
Is there any way to abstract this so we aren't doing the same as [src/AboutBlank.tsx](https://github.com/NebulaServices/Nebula/blob/main/src/AboutBlank.tsx#L4)

2024-01-01 16:34 UTC, IncognitoTGT commented on src/AboutBlank.tsx
>    iframe.style.height = "100%";
Could break shit if only left is specified

2024-01-01 16:34 UTC, IncognitoTGT commented on src/components/Header.tsx
> +              className="flex h-full w-full "
Outdated, I removed the whitespace

2024-01-01 16:38 UTC, IncognitoTGT commented on src/pages/Settings/TabSettings.tsx
> +              let newWindow = window.open("about:blank");
How to make stuff super complicated:
I copied AboutBlank.tsx but changed ` iframe.src = window.location.origin + props.url;` to remove `+ props.url`

2024-01-01 17:04 UTC, IncognitoTGT commented on src/pages/Settings/TabSettings.tsx
> +              let newWindow = window.open("about:blank");
So seems like a lot of the stuff in AboutBlank.tsx are specific to the direct aboutblank method so this will NOT work.

2024-01-01 17:09 UTC, cohenerickson approved these changes
good enough

2024-01-01 17:09 UTC, merged

2024-01-05 14:25 UTC, IncognitoTGT commented on src/pages/Settings/TabSettings.tsx
> +              let newWindow = window.open("about:blank");
skul it did work