PWA enabled
NebulaServices/Nebula pull request #89
Opened 2023-03-23 06:55 UTC by Nailington

In theory (tested in localhost enviro), this will allow PWAs on any fork of Neb

Now, is this needed, no not really. Does it make Nebula cooler? Who knows!? But it is the thought that counts, right? RIGHT???

2023-03-26 16:15 UTC, cohenerickson requested changes

2023-03-26 16:15 UTC, cohenerickson commented on app.js
> +app.get("/manifest", (req, res) => {
Could we move the manifest into the public folder instead of serving it as a separate route

2023-03-26 16:15 UTC, cohenerickson commented on public/resources/nebulamain.js
> +    scope: "/"
This should be a separate SW instead of registering the UV service worker on a different scope

2023-04-01 01:25 UTC, Nailington commented on app.js
> +app.get("/manifest", (req, res) => {
This has been properly relocated to the public folder, my bad!

2023-04-01 01:25 UTC, Nailington commented on public/resources/nebulamain.js
> +    scope: "/"
Scope reverted. New SW added

2023-04-27 15:23 UTC, GreenyDEV commented
Bump

2023-05-02 22:50 UTC, 830008 commented
Bump

2023-05-03 02:51 UTC, youngchief-btw commented
Why bump if it's less than a day? This is the only open PR. I'm sure the devs are busy.

2023-05-12 22:31 UTC, 830008 commented
I am the Head of Development for Nebula.

2023-05-12 23:42 UTC, GreenyDEV commented
currently waiting for cohens approval

2023-08-20 17:42 UTC, closed without merging